"""
Core domain models (Pydantic v2).

These are the internal data contracts used across agents, tools, and the DB layer.
They are NOT the API request/response schemas — those live in api/v1/schemas.py.

"""

from __future__ import annotations

from datetime import datetime
from typing import Annotated

from pydantic import BaseModel, Field, field_validator, model_validator


class InvoiceLineItem(BaseModel):
    """
    A single line item extracted from an invoice.

    Fields map directly to what GLM-OCR returns; confidence scores are integers 0–100
    using the same tier convention as SmartScanner (80 = supplier memory hit,
    60 = industry memory, < 60 = raw extraction).

    """

    description: str
    """Human-readable item description as extracted by OCR."""

    quantity: float | None = None
    """Item quantity. None when not present on the invoice."""

    unit_price: float | None = None
    """Price per unit in invoice currency. None when not extractable."""

    total_price: float | None = None
    """Line total (quantity × unit_price). Validated by tools/calculator.py."""

    unit: str | None = None
    """Unit of measure (e.g. 'kg', 'case', 'each'). None when absent."""

    confidence: Annotated[int, Field(ge=0, le=100)] = 0
    """Extraction confidence score (0–100). See coding-standards.md for tiers."""

    @field_validator("confidence")
    @classmethod
    def confidence_must_be_integer_tier(cls, v: int) -> int:
        """
        Reject float confidence scores — enforce integer-only convention.

        """
        # TODO: optionally warn if v is not one of the standard tiers (80, 60, 0)
        return v


class SupplierInfo(BaseModel):
    """
    Structured supplier profile used by the agent for context injection.

    In Restaurant OS this data comes from PostgreSQL via db/repositories.py (Section 6).

    """

    supplier_id: str
    """Immutable slug identifier. Must not contain '..', '/', or '\\'."""

    name: str
    """Display name as it appears on invoices."""

    category: str | None = None
    """Supplier category (e.g. 'seafood', 'produce'). Derived by agents/memory.py."""

    known_items: list[str] = Field(default_factory=list)
    """Previously seen item descriptions for this supplier (inference hints)."""

    @field_validator("supplier_id")
    @classmethod
    def no_path_traversal(cls, v: str) -> str:
        """
        Reject supplier IDs containing path traversal sequences.

        This check is preserved even though storage is now PostgreSQL, because supplier_id values still flow through file-name generation in some tools.
        """
        for forbidden in ("..", "/", "\\"):
            if forbidden in v:
                raise ValueError(f"supplier_id must not contain '{forbidden}'")
        return v


class ScanResult(BaseModel):
    """
    Full result of a single invoice scan run.

    Used by the scanner agent to assemble a structured response before returning to the FastAPI route handler (api/v1/routes.py → api/v1/schemas.py).
    """

    scan_id: str
    """Unique run identifier. Generated by the scanner agent at scan start."""

    supplier: SupplierInfo | None = None
    """Identified supplier. None when the agent cannot determine the supplier."""

    invoice_date: datetime | None = None
    """Invoice date extracted from the document. None when absent or unparseable."""

    line_items: list[InvoiceLineItem] = Field(default_factory=list)
    """All extracted line items. May be empty for unreadable invoices."""

    subtotal: float | None = None
    total: float | None = None
    tax: float | None = None

    overall_confidence: Annotated[int, Field(ge=0, le=100)] = 0
    """Aggregate confidence score across all extracted fields."""

    raw_ocr_text: str | None = None
    """Raw text returned by GLM-OCR before structured extraction."""

    scanned_at: datetime = Field(default_factory=datetime.utcnow)
    """UTC timestamp when the scan was performed."""

    @model_validator(mode="after")
    def validate_totals_consistency(self) -> ScanResult:
        """
        Warn when subtotal + tax does not match total (within tolerance).
        """
        # TODO: compare subtotal + tax to total within TOLERANCE from coding-standards
        # TODO: log a warning if mismatch exceeds tolerance (do not raise)
        return self


class ChatMessage(BaseModel):
    """
    A single turn in a restaurant operator's conversation with the agent.
    """

    role: str  # TODO: narrow to Literal["system", "user", "assistant", "tool"]
    """Message role as expected by the GLM chat API."""

    content: str | list
    """Message text or multimodal content list."""

    tool_call_id: str | None = None
    """Present only on role='tool' messages to correlate with the tool call."""


class RestaurantContext(BaseModel):
    """
    Restaurant-scoped context injected into every agent run.

    Loaded from PostgreSQL (db/repositories.py, Section 6) and passed through the LangGraph AgentState so every node has restaurant context available.

    """

    restaurant_id: str
    """Immutable restaurant identifier. Used as tenant_id in DB queries."""

    name: str
    """Restaurant display name for log messages and agent prompts."""

    known_suppliers: list[SupplierInfo] = Field(default_factory=list)
    """Pre-loaded supplier profiles for this restaurant (inference hints)."""

    cuisine_type: str | None = None
    """Cuisine category (e.g. 'Japanese', 'Italian'). Used for ingredient inference."""
